debug: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.board.boardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_NAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
#    datasource:
#      url: jdbc:mysql://localhost:3308/board?useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 1234
#      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf3.decoupled-logic: true


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        #dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

---